# This Dockerfile creates a simple Alpine Linux container that prints "Hello, World!" when run.

# Alpine is a base docker image & in top of that we are adding our image to print Hello, World!
FROM alpine:latest

CMD [ "echo", "Hello, World!" ] 
