version: "3.3"
services:
  mysql:
    image: mysql/mysql-server:8.0 # The Docker image to use for the MySQL service
    environment: # Environment variables passed into the MySQL container
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password" # (credentials can be initialized here; see the documentation for MySQL)
    ports:
      - "3306:3306" # Port mapping between the host and the container

  flaskapp:
    image: mysql:latest # The Docker image to use for the Flask application service
    depends_on:
      - mysql # Does this service depend on the creation of other services before it?
    environment:
      DATABASE_HOST: host.docker.internal
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME:
        db
        # Environment variables passed into the flask application
    ports:
      - 3000:3000 # Port mapping between the host and the container
